### PR TITLE
Making data generation changes in 1.17 without generated files

### PR DESCRIPTION
**Pull request by campbebj**
Here is the 1.17 version as discussed.
base blocks only.

I didnt make cobble cooking recipes so you shouldnt delete those files when you delete the blockstate folder, model folder, loot_table folder, and all the rest of the recipes.

You should also delete the en_us language file, and you can delete the others if you update the languageValues.config file to include other languages (and add the per language generation instance)

let me know if i forgot / missed anything. rebasing with the 1.17 changes was a pain.

### CODE REVIEW

**Comment by DinnerBeef** [comment]
Will look at this tomorrow

**Comment by DinnerBeef** [comment]
Block Hardness is broken for everything but fallingblocks

**Comment by campbebj** [comment]
Interseting. ill take a look. it should have been part of the block behavior copy from the baseline.

**Comment by DinnerBeef** [comment]
I will say this though. Each block got it Hardness and mining level from the block it was compressing before. So sand needed a shovel and stone needed a pickaxe they should all the the same

**Comment by DinnerBeef** [comment]
Fixing this my self.

**Comment by DinnerBeef** [comment]
going to look more at this later but i need to fix something first

**Comment by DinnerBeef** [comment]
o forge broke shit so i might be able to use this now LOL

**Pull request merged**
